spring:
  application:
    name: config-server

  profiles:
    active: native, git

  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/pintech/sparta/2th_infra/msa_infra/project-configs
        git:
          uri: https://github.com/junhyeong9812/project-configs
          default-label: main
          search-paths:
            - configs
            - configs/**
          basedir: configs
          clone-on-start: true

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE:http://localhost:3150/eureka/}

server:
  port: 3100